repo_url: https://flclash.eykettle.top/repo
repo_name: FlClash
repo_description: >-
  Unofficial F-Droid repository for the EyKettle fork of FlClash.

repo_keyalias: KEYALIAS
keystore: keystore.keystore
keystorepass: KEYSTOREPASS
keypass: KEYPASS
keydname: KEYDNAME

# archive: keep at most 5 versions in main repo
archive_older: 5
